# vim: set ft=rb:

class self
  def @main()
    try
      throw("Error")
    catch(msg : String)
      trace("Error occurred: " + msg)
    end
  end
end
